image:
  file: .gitpod.Dockerfile
ports:
  - port: 6080
    onOpen: open-preview
  - port: 35900
    onOpen: ignore
  - port: 5900
    onOpen: ignore
tasks:
  - init: >
      npm install &&
      npm install -g vsce &&
      echo "y" | vsce package
  - command: alias code=code; code --install-extension helloworld* && code
vscode:
  extensions:
    - Sean.helloworld@0.0.2:Mj+iYu7eJXobeMLpWzUo0Q==