image:
  file: .gitpod.Dockerfile
ports:
  - port: 6080
    onOpen: open-preview
  - port: 35900
    onOpen: ignore
  - port: 5900
    onOpen: ignore
tasks:
  - init: >
      npm install &&
      npm install -g vsce &&
      echo "y" | vsce package &&

vscode:
  extensions:
    - vscjava.vscode-java-debug@0.24.0:4bjzZag4ZW2bFcv6qiRCEg==
    - Sean.helloworld@0.0.1:06AfByinrblOZJaKpXRyCw==