image:
  file: .gitpod.Dockerfile
ports:
  - port: 6080
    onOpen: open-preview
  - port: 35900
    onOpen: ignore
  - port: 5900
    onOpen: ignore
tasks:
  - init: npm install && unalias code
    command: code .